# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkinvitation',
            name='invitations_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='decline_invitaion',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='decline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='invalid_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membershipinvitation',
            name='accepted_invitation',
            field=models.NullBooleanField(),
        ),
    ]
