# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_roles', '0003_auto_20180427_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipinvitation',
            old_name='decline_invitaion',
            new_name='decline_invitation',
        ),
    ]
