# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('django_roles', '0007_auto_20180428_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrlPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(to='auth.Permission')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_roles.ProjectUrl')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
