# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_roles', '0008_projecturl_urlpermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlPermission',
            new_name='UrlPermissionRequired',
        ),
    ]
